"
segini p=q, which will first allocate memory space for p and copy the contents of q into p


"
Class {
	#name : 'FASTEsopeSegcop',
	#superclass : 'FASTEsopeSegCommand',
	#category : 'FAST-Esope-Entities-Entities',
	#package : 'FAST-Esope-Entities',
	#tag : 'Entities'
}

{ #category : 'meta' }
FASTEsopeSegcop class >> annotation [

	<FMClass: #Segcop super: #FASTEsopeSegCommand>
	<package: #'FAST-Esope-Entities'>
	<generated>
	^ self
]
