"
I represent a slash operator ptr.attr(/1)


"
Class {
	#name : 'FASTEsopeArrayDimensionExpression',
	#superclass : 'FASTFortranBinaryExpression',
	#category : 'FAST-Esope-Entities-Entities',
	#package : 'FAST-Esope-Entities',
	#tag : 'Entities'
}

{ #category : 'meta' }
FASTEsopeArrayDimensionExpression class >> annotation [

	<FMClass: #ArrayDimensionExpression super: #FASTFortranBinaryExpression>
	<package: #'FAST-Esope-Entities'>
	<generated>
	^ self
]
